version: '3.2'
services:
  app:
    build:
      context: ./docker/go
    restart: on-failure
    working_dir: /go/src/myapp
    ports:
      - 127.0.0.1:8074:8074
    volumes:
      - ./backend/:/go/src/myapp

  redis:
    build:
      context: ./docker/redis
    ports:
      - 127.0.0.1:6379:6379
    restart: on-failure
